// Generated by CoffeeScript 1.8.0
(function() {
  var parse, readFileSync;

  readFileSync = require("fs").readFileSync;

  parse = require("./parse");

  module.exports = function(path, query) {
    var current, key, root;
    current = root = parse((readFileSync(path)).toString());
    while (query.length > 0 && (current != null)) {
      key = query.shift();
      current = current[key];
    }
    return console.log(JSON.stringify(current, null, 2));
  };

}).call(this);
